_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
architecture:
    value: MLP
batch_size:
    value: 20
epochs:
    value: 20
sequence_lenth:
    value: 1200
